  11-connect-the-flask-server-to-the-database[m
  12-fix-error-in-the-create-database-script[m
  13-fix-truncate-issue-with-the-database[m
  14-create-login[m
  16-sent-emails[m
  19-full-list-of-price-test-date[m
  21-modify-the-table-design[m
  23-combine-sql-commands[m
  27-securelink[m
  29-code-decrypted[m
  3-set-up-flask-server[m
  32-record-new-customer-in-database[m
  32-records-details-on-database[m
  36-checkout-button[m
  37-purchase-multiple-licences[m
  4-create-jinja-template[m
  42-verify-email-address[m
  43-customer-login[m
  45-customer-template[m
  46-price-negotiated[m
  47-admin-template[m
  5-list-of-licences[m
  7-get-type-of-licence[m
  7-select-licence[m
  9-adds-licence-basket[m
  9-purchase-recorded[m
  9-record-purchase[m
  Quick-fix-number-employees[m
  attempt2[m
  fix-errors-with-template[m
* [32mmaster[m
  test-form-payment[m
